### ISSUE TITLE
-d option causes syntax error with -b

### ISSUE THREAD

**Issue by tripleee** [saffsd/langid.py#19]
The `-d` option produces a syntax error if you attempt to use it with `-b`; it refers to a variable `nb_classes` which was probably in scope before the code was refactored. (It does exist in some other methods but I am unable to figure out how to stitch it back together.)

```
 vnix$ ./langid/langid.py -d -b sample.txt
Traceback (most recent call last):
  File "./langid/langid.py", line 587, in <module>
    main()
  File "./langid/langid.py", line 558, in main
    writer.writerow(['path']+nb_classes)
NameError: global name 'nb_classes' is not defined
```

**Comment by carschno** [comment]
Looks like 600f5308de533d82ed3363fb2cd93cd11774bf7b re-introduces this issue.
