### ISSUE TITLE
pip install langid does not work

### ISSUE THREAD

**Issue by Stophface** [saffsd/langid.py#27]
Hello,
I try to install the library with pip on OS X 10.6, python 3.3.
Running the pip command I receive the following.

    $ pip install langid
    Downloading/unpacking langid
    Could not find a version that satisfies the requirement langid (from versions: 1.0dev, 1.1.1dev, 1.1.2dev, 1.1.3dev, 1.1.4dev, 1.1dev)
    Cleaning up...
    No distributions matching the version for langid
    Storing debug log for failure in /Users/xx/.pip/pip.log

So I downloaded the package and tried to install it without pip
      
    $ python setup.py install

Looked good until here:

    Extracting langid-1.1.4dev-py2.6.egg to /Library/Python/2.6/site-packages
    SyntaxError: ('invalid syntax', ('/Library/Python/2.6/site-packages/langid-1.1.4dev-py2.6.egg/langid/train/common.py', 39, 34, "  with gzip.open(path, 'rb') as f, tempfile.TemporaryFile() as t:\n"))

    Adding langid 1.1.4dev to easy-install.pth file
    error: /Library/Python/2.6/site-packages/easy-install.pth: Permission denied

Why isnt it installing? Furthermore, I dont want it to install with python 2.6 (I guess thats the default python version of OS X 10.6) but with python 3.3

**Comment by Stophface** [comment]
That did not work for me (`pip install --pre langid`).
It installed it, but importing came an error message. Something with the `__init__.py` file is wrong. It could not import it. 
So I replaced the `langid.py` file (you`ll find it in the site-package folder) with that one 
https://raw.githubusercontent.com/saffsd/langid.py/python3/langid/langid.py and had a look at the `__init__.py` file. There seems to be a dot (`.`) missing in front of `langid`.
So it says `from langid import classify, rank, set_languages`. I wrote it like that `from .langid import classify, rank, set_languages`.
Now when I try to import it with `import langid` in the Python IDLE there are no error messages.

That might be useful for someone who comes across this.

**Comment by selahlynch** [comment]
Had installation issues also...
http://stackoverflow.com/questions/29685627/how-do-i-install-langid-python-library-from-github

Ended up just downloading the zip and installing manually.

**Comment by hakanw** [comment]
Is the problem here that the version number on pypi is e.g. "1.1.4dev" while "1.1.4" is specified in the setup.py?

**Comment by saffsd** [comment]
Fixing #35 should make `pip install langid` work as expected now.
