### ISSUE TITLE
Add support for python3

### ISSUE THREAD

**Issue by frederik-elwert** [saffsd/langid.py#28]
Currently, langid fails to import when running python3.

**Comment by saffsd** [comment]
Hi Frederik,

Thanks for reporting the issue. There is a branch that works in Python 3 [here](https://github.com/saffsd/langid.py/tree/python3). I'd very much like to have a single codebase that runs in both Python 2/3 but I've not had a chance to look into how to do this. If you have any experience in this respect any patches would be appreciated.

Cheers,
Marco

**Comment by frederik-elwert** [comment]
Thanks, works perfectly!

Re 2/3: I guess using [six](https://pythonhosted.org/six/) would be the easiest way to achieve that.

**Comment by adampl** [comment]
That branch is not fully Python 3 compatible. There is a lot of syntax errors caused by prints without parentheses. To see them, just run `pip install https://github.com/saffsd/langid.py/archive/python3.zip`.

**Comment by saffsd** [comment]
Hi Adam,

Thanks for getting in touch. You're right that the port is incomplete,
currently only the core classifier langid.py itself has been ported, the
supporting tools for model building have not. You should be able to use the
file `langid.py` from that branch in a python3 project.

**Comment by rrshaban** [comment]
@adampl Given that Python2 supports print with parantheses, why not just convert all the print statements to parantheses? Or maybe this has already been done, it's been a couple of months.

**Comment by adampl** [comment]
@rrshaban There may be other incompatibilities as well, prints are just the most obvious ones.

**Comment by saffsd** [comment]
As of 600f5308de533d82ed3363fb2cd93cd11774bf7b the core script `langid/langid.py` runs in both Python2 and Python3 interpreters. Porting the training tools is a bigger job and not in my workplan at the moment. I'll mark this as closed for now.
