### ISSUE TITLE
Fix pypi classifiers

### ISSUE THREAD

**Issue by pquentin** [saffsd/langid.py#34]
Your setup.py file does not define any pypi classifier, which I think prevents `pip3 install --pre langid`. Here is the list: http://pypi.python.org/pypi?%3Aaction=list_classifiers. I think we should start with:

```
Programming Language :: Python :: 2
Programming Language :: Python :: 2.7
Programming Language :: Python :: 3
```

This would fix the Python 3 issue. But since we're on such a good start, we could continue.

You then need to choose a status. Either Beta or Production/Stable, probably Production/Stable.

```
Development Status :: 4 - Beta
Development Status :: 5 - Production/Stable
```

Then, an intended audience. I suggest:

```
Intended Audience :: Developers
Intended Audience :: Science/Research
```

Then the license. Is your custom license OSI Approved?

And finally a topic:

```
Topic :: Scientific/Engineering :: Artificial Intelligence
```

Once you tell me your choices, I can send a pull request. Thanks!

**Comment by saffsd** [comment]
Thanks for volunteering to help! 

I think Production/Stable is fine for this project. 

The license is not meant to be custom, it is meant to be [BSD 2-Clause](http://opensource.org/licenses/BSD-2-Clause). Please let me know if that's not set up right. 

With respect to Topic, would

 `Topic :: Text Processing :: Linguistic`

Also apply? I'm not familiar with how these identifiers are used.

**Comment by pquentin** [comment]
Sure, the topic also seems to apply.

Sorry for the license, I chose 'BSD' as was done in the arguments to `setup()`, since there's no way to choose between 2-clause and 3-clause.

**Comment by pquentin** [comment]
@saffsd any progress on this?

**Comment by saffsd** [comment]
Sorry for the delay, it fell off my radar. Going to try and sort #35 now.

**Comment by pquentin** [comment]
Thank you @saffsd!
