### ISSUE TITLE
Fix versioning

### ISSUE THREAD

**Issue by pquentin** [saffsd/langid.py#35]
Your versioning scheme is not PEP 440 compliant, which means than many people, as you have noticed, have issues when installing langid.py with pip.

First, 1.1.4dev is not valid, you [need to use `1.1.4.dev0` instead](https://www.python.org/dev/peps/pep-0440/#developmental-release).

Second, is there any good reason to choose a `dev` suffix? Can you simply remove `tag_build = dev` from setup.cfg before releases?

Thanks!

**Comment by saffsd** [comment]
Thanks for the input - I've been wondering where that 'dev' suffix came from but never got round to investigating. I'd like to get rid of it. What do you think is the best way to do this? Here's my rough plan:

1) remove tag from setup.cfg
2) integrate pypi classifiers fix from #34 
3) package and release onto pypi as 1.1.4

Very open to suggestions!

**Comment by pquentin** [comment]
Sounds great! For 3), I would releases this as 1.1.5, since for me the current release is '1.1.4'.

**Comment by saffsd** [comment]
Thanks for the suggestions. I've implemented the changes as suggested and released as 1.1.5. In my limited testing `pip install langid` now works smoothly!

**Comment by nathanleiby** [comment]
:100:

**Comment by pquentin** [comment]
:clap:
