### ISSUE TITLE
Should langid.py return probabilities?

### ISSUE THREAD

**Issue by pquentin** [saffsd/langid.py#36]
When running langid.py directly, I get negative numbers, which are different from the `0.99` mentioned in the docs. Should I expect a number between zero and one?

```
$ python3 langid.py < ../README.rst
('en', -21016.57295703888)
$ python2.7 langid.py < ../README.rst
('en', -21016.57295703888)
```

Do the smallest values win?

```
$ python langid.py
>>> the
('en', 9.061840057373047)
>>> the the the the the the the the the the
('en', -240.49303674697876)
```

Thanks!

**Comment by saffsd** [comment]
There's a flag `-n` to enable probability normalization for command-line use:

https://github.com/saffsd/langid.py/blob/master/README.rst#probability-normalization

It's disabled by default for command-line use as it doesn't change the language that `langid.py` outputs, it only helps with the interpretation of the output value.

Please re-open this issue if that doesn't work for you.

**Comment by pquentin** [comment]
Perfect, thank you!

**Comment by Pala-beh** [comment]
Could you tell me how to normalize the values in case we work on a notebook?
I would like an equivalent of "python langid.py -n ..." for the notebook

Thanks
