### ISSUE TITLE
Runtimewarning freeze uwsgi worker

### ISSUE THREAD

**Issue by jnieuviarts** [saffsd/langid.py#43]
Thank you for this nice lib.
We are using langid with a webservice and are facing a really weird problem : from time to time, the uwsgi worker is killed because of this portion of code : 
```python
with np.errstate(over='ignore'):
    pd = (1/np.exp(pd[None,:] - pd[:,None]).sum(1))
return pd
```
After a few googling, we found this message : 
http://stackoverflow.com/questions/19213768/numpy-runtime-warning-causing-apache-workers-to-freeze-in-sending-reply-state
It seems that there is something with warning and numpy

As we are on nginx, the proposed fix is not working.
Do you have any idea of how we could workd around this ?

**Comment by saffsd** [comment]
Hi Jerry, thanks for getting in touch. Interesting issue! Do you actually use the probability estimates? If all you need is the predicted language, then turning off probability normalization will disable that specific bit of code.

**Comment by jnieuviarts** [comment]
Thank you very much for your answer. By the way, we are testing another way
to bypass the problem. If this works well, we'll push a PR to your package.
Best regards.
Jerry

[image: Mapado] <http://www.mapado.com>

Jerry Nieuviarts
co-fondateur
+33 6 82 37 42 71

MAPADO <http://www.mapado.com> Occupez-vous ! [image: Facebook]
<http://www.facebook.com/MapadoFrance> [image: Twitter]
<http://twitter.com/Mapado_com>


2015-11-20 21:23 GMT+01:00 saffsd <notifications@github.com>:

**Comment by dav009** [comment]
@jnieuviarts In my experience with UWSGI you should be careful when using multiprocessing or threads.
I assume np is using multiprocessing under the hood which should have no problems with UWSGI, however if you are using threads in your webapp (somewhere on top) this might run into conflicts depending on your UWSGI config.

i.e: https://github.com/unbit/uwsgi/issues/634
These goes in hand with

**Comment by saffsd** [comment]
Closing as this has been inactive for some time.
