### ISSUE TITLE
Weird classification for Latvian & ex-Yougoslavian languages

### ISSUE THREAD

**Issue by plison** [saffsd/langid.py#44]
Hi,

I noticed some weird classification problems for Latvian, the text (a subtitle) being typically classified as Luxemburgish (!). As the codes for the two languages follow each other, I was wondering whether this might be due to a bug (in the training data or the classifier)? 

Bosnian, Croatian and Serbian are also difficult to classify (these languages being very close, and until recently often classified as one single language). However, it seems that the classification of Croatian "overweights" the two other languages -- if I try to classify Bosnian and Serbian subtitles, I typically get Croatian as only possible language.

**Comment by saffsd** [comment]
Hi Pierre,

Thanks for getting in touch! Misclassifying Latvian to Luxemburgish does indeed seem strange. I'm not familiar with either language but it's not a confusion pair I have heard of before, so it seems quite plausible that there may be some incorrectly labeled training data. Could you share some examples of incorrectly-labeled sentences?

As for Bosnian/Serbian/Croatian, this confusion set is more well-known (see [1]) and is notoriously quite difficult. 

Let me know more details of your use case, and I'll try to offer some advice on how to increase accuracy.

[1] http://nlp.ffzg.hr/data/publications/nljubesi/tiedemann12-efficient.pdf

**Comment by plison** [comment]
Thanks for the answer! It seems the classification problem with Latvian comes from an encoding mistake on my part (used the wrong encoding format to decode the file).  So everything looks fine now, I'm closing the issue!
