### ISSUE TITLE
Poor classification with mono-cased text

### ISSUE THREAD

**Issue by az0** [saffsd/langid.py#47]
I am classifying 3 million texts, and usually classification performance is good. However, for a few texts that are all uppercase, performance is very poor. Here is a toy example

````
>>> import langid
>>> print langid.classify('The quick brown fox jumps over the lazy dog')
('en', 0.9999999999138445)
>>> print langid.classify('THE QUICK BROWN FOX JUMPS OVER THE LAZY DOG')
('pl', 0.4406207245841342)
````

Also, all lowercase text can have poor performance
````
>>> print langid.classify('I do not speak English. Do you?')
('en', 0.9071235348010346)
>>> print langid.classify('i do not speak English. do you?')
('pt', 0.9283325957561123)
````

Do you think langid should be retrained on all-capitalized and all-lowercase examples? This is analogous to how image classification training sets are augmented by distorting the original images through transformations such as mirroring or warping.

**Comment by creaforge** [comment]
Same here, I got around 99,8% or right classification (which is amazing by the way) and the few leftovers are mono-cased ones. Another example in french :

```
"TEST DE DÉTECTION DE LANGUE EN FRANÇAIS"  > en (0.16946150595865334)
"Test de détection de langue en Français"  > fr (0.9999417848679748)
```

**Comment by saffsd** [comment]
Thanks for the suggestion! Sorry it has taken awhile to address it. It is certainly possible to do so but I would be hesitant to do it as it would require some testing to understand how this would impact accuracy on normally-cased text. I suspect it would be easier to do case detection and normalization as a pre-processing step, and then feed this into the language identifier.
