### ISSUE TITLE
broken link in README

### ISSUE THREAD

**Issue by az0** [saffsd/langid.py#48]
http://www.csse.unimelb.edu.au/~mlui

Server not found

**Comment by tripleee** [comment]
Many others in the same research group seem to have broken home page links at http://www.cs.mu.oz.au/research/lt/

**Comment by saffsd** [comment]
Thanks for pointing it out! I've removed the link from the README, unfortunately due to various re-organizations at the Unimelb a number of pages have been discontinued.
