### ISSUE TITLE
Can you tell me how to identify those 97 languages?

### ISSUE THREAD

**Issue by winter-loo** [saffsd/langid.py#53]
As written in README, langid.py comes pre-trained on 97 languages. How could I reproduce the conclusion? I gave a try for UG language, but it told me it's ZH.  I attempted to test JA language,  it reported error:

```
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 21: illegal multibyte sequence
```

So, the problem is how to reproduce your conclusion? Thanks in advance.

**Comment by adjkldd** [comment]
In interactive mode, it works well. However, while reading from file : 

    python langid.py -n < Chinese.txt

It reports the above error

**Comment by zafercavdar** [comment]
Python2 has problems with decoding non-ASCII unicode characters. Instead of using python2, try to run `langid` with Python3.
