### ISSUE TITLE
Distinguish between Simplified Chinese and Traditional Chinese

### ISSUE THREAD

**Issue by BLKSerene** [saffsd/langid.py#70]
Hi, as there are two written forms of Norwegian (Bokmål and Nynorsk), Chinese are written in either Simplified characters or Traditional ones.
Is it possible for langid to distinguish between them?

**Comment by zhuangyuyang** [comment]
same question.

**Comment by Jefffish09** [comment]
Same question, Do langid supports to distinguish Simplified Chinese and Traditional Chinese now?
